version: "3"
services:
  matsumoto-front:
    build: .
    container_name: web
    networks:
      matsumoto_net:
        aliases:
          - nginx    
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/jaeger-config.json:/etc/jaeger-config.json

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      matsumoto_net:
        aliases:
          - jaeger
    expose:
      - "9411"
      - "16686"
    ports:
      - "9411:9411"
      - "16686:16686"

networks:
  matsumoto_net: {}      