apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    ingress.kubernetes.io/force-ssl-redirect: "true"    
spec:
  tls:
  - secretName: letsencrypt-{{ .Release.Namespace }}-{{ .Chart.Name }}
    hosts: 
    - {{ .Release.Namespace }}.{{ .Values.root_url }}
    - {{ .Values.root_url }}
  rules:
  - host: {{ .Release.Namespace }}.{{ .Values.root_url }}
    http:
      paths:
      - backend:
          serviceName: {{ .Chart.Name }}
          servicePort: 80
        path: /
  - host: {{ .Values.root_url }}
    http:
      paths:
      - backend:
          serviceName: {{ .Chart.Name }}
          servicePort: 80
        path: /        